### ISSUE TITLE
need better validations and assertions

### ISSUE THREAD

**Issue by vishaljoshi** [vishaljoshi/TestTheRest#2]
need some standard function to validate like
1. is number
2. is float
3. is string
4. startsWith
5. endsWith
6. contains
7. regular Expression

**Comment by pksoman** [comment]
More things which can make it powerful :  
1. Null check for String
2. Count of elements in an array
3. Contains check within an array
4. Currently Assertion can be done only on successful response. Should be able to validate content in the Error response aswell.
5. Should be able to assert error response code.

**Comment by vishaljoshi** [comment]
function available now:
isNumber() 
isFloat()
isString();
has();
arrayLength();
arrayHas();
regTest()

will update the usage details shortly
http://run.plnkr.co/plunks/WzyzgCufb8zmDWWjGh8E/testAssertions.html

**Comment by vishaljoshi** [comment]
all the issue are fixed and published
